
name: CIx
on: 
  push:
    branches: [ main ]
  schedule:
    - cron: "*/13 * * * *"
jobs:
  satu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set current date
        id: date
        run: echo "::set-output name=date::$(echo $RANDOM | md5sum | head -c 1; echo;)"

      - name: Create commits
        run: |          
          echo $RANDOM | md5sum | head -c 8; echo;
          TTT=$(echo $RANDOM | md5sum | head -c 8;)
          echo " $TTT " > Jess
          echo $TTT
          echo " $RANDOM " > file
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.date.outputs.date }}
          title: ${{ steps.date.outputs.date }}
